// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const SUPABASE_URL = "https://emziqfhzysyovohelvht.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtemlxZmh6eXN5b3ZvaGVsdmh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2ODE0NTAsImV4cCI6MjA2NTI1NzQ1MH0.CsHMB3-aEKS2jx5X4ZEp5u_1hbZCZU0IcMwYYEjHpFk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});